const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const src = fs.readFileSync(process.argv[2] || 'app/static/project_mission.js', 'utf8');
const render = src.slice(src.indexOf('  function renderPremarketing(){'), src.indexOf('  async function loadPremarketing(){'));
let writes = 0, details = [{open: true}];
const box = {dataset: {renderProject: 'p'}, querySelectorAll(selector) {return selector === 'details' ? details : [];}, set innerHTML(value) {writes++; details = [{open:false}];}};
const ctx = {currentProject:'p', premarketing:{campaigns:[],leads:[]}, el:()=>box, escapeHtml:String};
vm.createContext(ctx);
vm.runInContext(render, ctx);
ctx.renderPremarketing();
assert.equal(details[0].open, true, 'retain expanded kit after changed data');
ctx.renderPremarketing();
assert.equal(writes, 1, 'unchanged data must not replace DOM');
ctx.premarketing.google = {configured:true};
ctx.renderPremarketing();
assert.equal(writes, 2);
assert.equal(details[0].open, true);
ctx.currentProject = 'other';
ctx.renderPremarketing();
assert.equal(details[0].open, false, 'do not transfer expanded state across projects');
const missionLoad = src.slice(src.indexOf('  async function loadMission('), src.indexOf('  async function loadMission(')+1200);
assert.match(missionLoad, /if\(forceFields\|\|.*renderProject!==target\)loadPremarketing\(\)/);
assert.match(src, /intent=newBrowser&url=/, 'Google Sites must open through dedicated Chrome');
assert.match(src, /encodeURIComponent\(publisherTarget\)/, 'edit URL must be encoded');
assert.doesNotMatch(src, /href="'\+escapeHtml\(c\.google_site_edit_url\|\|"http:\/\/127\.0\.0\.1:8010"\)/,
  'Google Sites edit URL must not open in the ordinary browser');
assert.match(src, /data-social-regenerate/, 'existing social kits need a regeneration action');
assert.match(src, /旧版はアーカイブ済みです/, 'regeneration must report archive preservation');
assert.match(src, /投稿証拠あり/, 'published social evidence must block destructive regeneration');
console.log('PASS: unchanged DOM, expanded state, project isolation, no 1-second premarketing reload');
