"""Vehicle monthly P&L GoalContract template (C01-C12)."""
from __future__ import annotations

TEMPLATE_ID = "vehicle_monthly_pnl/v1"

CRITERIA = [
    {
        "criterion_id": "C01",
        "statement": "対象会社・期間・車両が確定している",
        "type": "factual",
        "test_method": "scope_evidence",
        "required_evidence": ["vehicle_register", "period_in_goal"],
        "human_decision_required": False,
        "weight": 1.0,
        "topics": ["対象", "期間", "車両", "会社"],
        "exec_task_keys": ["SC00", "vehicle_extract"],
        "verify_task_keys": ["final_verification"],
    },
    {
        "criterion_id": "C02",
        "statement": "全車両について全対象月の行が存在する",
        "type": "computational",
        "test_method": "coverage_check",
        "required_evidence": ["calculation_rows"],
        "human_decision_required": False,
        "weight": 1.0,
        "topics": ["全車両", "月別"],
        "exec_task_keys": ["vehicle_calculate"],
        "verify_task_keys": ["final_verification"],
    },
    {
        "criterion_id": "C03",
        "statement": "売上、燃料、リース、人件費、会社負担社会保険、その他費目が定義済みである",
        "type": "factual",
        "test_method": "category_schema",
        "required_evidence": ["required_categories"],
        "human_decision_required": False,
        "weight": 1.0,
        "topics": ["売上", "燃料", "リース", "給与", "人件費", "社会保険"],
        "exec_task_keys": ["vehicle_extract"],
        "verify_task_keys": ["final_verification"],
    },
    {
        "criterion_id": "C04",
        "statement": "給与と社会保険が承認済み車両配布ルールで集計されている",
        "type": "computational",
        "test_method": "allocation_rules",
        "required_evidence": ["allocation_rules", "input_allocation_reconciled"],
        "human_decision_required": True,
        "weight": 1.2,
        "topics": ["配賦", "給与", "社会保険"],
        "exec_task_keys": ["vehicle_calculate"],
        "verify_task_keys": ["final_verification"],
    },
    {
        "criterion_id": "C05",
        "statement": "燃料費が月別原本と車番対応に基づく",
        "type": "computational",
        "test_method": "fuel_source_map",
        "required_evidence": ["source_locator", "vehicle_match"],
        "human_decision_required": False,
        "weight": 1.0,
        "topics": ["燃料", "車番"],
        "exec_task_keys": ["vehicle_extract"],
        "verify_task_keys": ["final_verification"],
    },
    {
        "criterion_id": "C06",
        "statement": "リース額を保持し、税込であることを明記している",
        "type": "computational",
        "test_method": "lease_tax_note",
        "required_evidence": ["lease_amount", "inclusive_note"],
        "human_decision_required": False,
        "weight": 0.8,
        "topics": ["リース", "税込"],
        "exec_task_keys": ["vehicle_calculate"],
        "verify_task_keys": ["final_verification"],
    },
    {
        "criterion_id": "C07",
        "statement": "車両別月次損益と会社合計を生成している",
        "type": "computational",
        "test_method": "independent_profit_match",
        "required_evidence": ["profit.xlsx", "independent_profit_match"],
        "human_decision_required": False,
        "weight": 1.2,
        "topics": ["損益", "合計", "Excel"],
        "exec_task_keys": ["vehicle_calculate"],
        "verify_task_keys": ["final_verification"],
    },
    {
        "criterion_id": "C08",
        "statement": "車両ごとのシートを生成している",
        "type": "computational",
        "test_method": "vehicle_summary_match",
        "required_evidence": ["vehicle_sheets"],
        "human_decision_required": False,
        "weight": 0.8,
        "topics": ["シート", "車両別"],
        "exec_task_keys": ["vehicle_calculate"],
        "verify_task_keys": ["final_verification"],
    },
    {
        "criterion_id": "C09",
        "statement": "元帳、請求単位、配賦前後、会社合計の独立照合がPASSである",
        "type": "computational",
        "test_method": "source_reconciliation",
        "required_evidence": ["source_reconciliation"],
        "human_decision_required": False,
        "weight": 1.4,
        "topics": ["照合", "原本", "統制"],
        "exec_task_keys": ["vehicle_calculate"],
        "verify_task_keys": ["final_verification"],
    },
    {
        "criterion_id": "C10",
        "statement": "未配賦、読取失敗、照合不能、根拠不明が0である",
        "type": "factual",
        "test_method": "unresolved_zero",
        "required_evidence": ["unresolved_counts"],
        "human_decision_required": False,
        "weight": 1.4,
        "topics": ["未配賦", "読取", "不足"],
        "exec_task_keys": ["vehicle_extract", "vehicle_calculate"],
        "verify_task_keys": ["final_verification"],
    },
    {
        "criterion_id": "C11",
        "statement": "Excel再計算が可能で数式エラーが0である",
        "type": "computational",
        "test_method": "recalculation",
        "required_evidence": ["recalculation"],
        "human_decision_required": False,
        "weight": 1.0,
        "topics": ["再計算", "数式"],
        "exec_task_keys": ["vehicle_calculate"],
        "verify_task_keys": ["final_verification"],
    },
    {
        "criterion_id": "C12",
        "statement": "主要金額を原本まで追跡できる",
        "type": "factual",
        "test_method": "evidence_graph",
        "required_evidence": ["source_locator", "source_ref"],
        "human_decision_required": False,
        "weight": 1.0,
        "topics": ["根拠", "原本", "追跡"],
        "exec_task_keys": ["vehicle_extract"],
        "verify_task_keys": ["final_verification"],
    },
]


TOPIC_PATTERNS = {
    "period": ("期間", "年から", "月まで", "対象月"),
    "vehicle": ("車両", "車番"),
    "company": ("会社", "対象会社"),
    "payroll": ("給与", "人件費", "賃金"),
    "insurance": ("社会保険", "社保", "会社負担"),
    "fuel": ("燃料",),
    "lease": ("リース",),
    "tax_inclusive": ("税込",),
    "sheet": ("シート", "車両別"),
    "reconcile": ("照合", "統制"),
    "allocation": ("配賦", "未配賦", "按分"),
    "trace": ("根拠", "追跡", "原本"),
}


def present_topics(text: str) -> set[str]:
    return {key for key, words in TOPIC_PATTERNS.items() if any(word in text for word in words)}
